[config]
# If set to enabled, it will check for updates when you run the matugen command, notifying you that an update is avaiable.
# WARNING: Matugen needs to be compiled with the `update-informer` feature for this to work.
version_check = false

[templates.vesktop]
input_path = "~/.config/matugen/templates/discord.css"
output_path = "~/.config/vesktop/themes/HyprNoon.css"
